### ISSUE TITLE
Adapt into "official" Raylib learning resource 

### ISSUE THREAD

**Issue by Nezteb** [raysan5/challenges#10]
I mentioned [this in the Raylib Discord](https://discord.com/channels/426912293134270465/877977601577197578/1157035358765199451), but I figured I'd make a GitHub issue too.

> **Ray — 09/28/2023 20:25 UTC**
> that was the materials I created for a University subject I taught for some time
> actually it was more focused to OpenGL
> but yeah, I never promoted it around

There's also [a PR to add a link to this challenges repo to the official website](https://github.com/raysan5/raylib.com/pull/64), but Ray might have things they want to change about the challenges to make it more specific to Raylib as a form of guide/documentation. This issue is meant to discuss any potential changes needed. 😄

**Comment by raysan5** [comment]
At this moment there is plans to change this repo neither include it in the official raylib webpage. Afaik, it's still being used by the University on its form and it shouldn't be touched.
