### ISSUE TITLE
Malformed URL?

### ISSUE THREAD

**Issue by abu-noor** [raysan5/challenges#5]
Under "Videogame life cycle", the diagram isn't visible.

"basic_game template" points to 404 as well. I did manage to find it in a 2017 repository under "templates"

Final edit, I promise. Chapter 5: just before the embedded source code. "like in the case of heightmaps." Another 404.

I'm just look for a tutorial for my daughter to follow. I figured these challenges would be good for her. Wanted to see if I can get the 404s fixed before I show her these.

**Comment by raysan5** [comment]
@abu-noor Thanks for reporting! Reviewed all issues!
